name: Codeception Tests

on:
  push:
    branches-ignore:
      - gh-pages

jobs:
  acceptance:
    runs-on: ubuntu-18.04

    services:
      mariadb:
        image: mariadb:10.3  # 10.3, 10.5, 10.6
        env:
          MARIADB_USER: turkuaz
          MARIADB_PASSWORD: turkuaz
          MARIADB_DATABASE: turkuaz_development
          MARIADB_RANDOM_ROOT_PASSWORD: "true"
        ports:
          - 3306:3306

      selenium-firefox:
        image: selenium/standalone-firefox:4.4
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - 4444:4444
        options: >-
          --health-cmd "curl -f http://localhost:4444/wd/hub/status"
          --health-interval 30s
          --health-timeout 10s
          --health-retries 5
          --health-start-period 30s

    strategy:
      matrix:
        php: [ "7.4" ]

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: >-
            mbstring, dom, fileinfo, mysql, libxml, xml, xmlwriter, dom,
            tokenizer, filter, json, phar, pcre, openssl, pdo, intl,
            curl
          ini-values: memory_limit=-1, date.timezone='UTC'
          coverage: xdebug
          tools: composer:v2

      - name: Start Apache HTTP Server unit
        run: sudo systemctl start apache2.service

      - name: Symlink GitHub Workspace to Apache HTTP Server webroot
        run: |
          sudo rm -rf /var/www/html
          sudo ln -s $GITHUB_WORKSPACE /var/www/html

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      - name: Check Selenium health status
        run: curl -f http://selenium-firefox:4444/wd/hub/status

      - name: Run Acceptance tests
        run: php vendor/bin/codecept run tests/acceptance/SetupWizardCest.php --steps
